--- 
apiVersion: apps/v1
kind: Deployment
metadata: 
  labels: 
    app: currencyconfigserver
    version: v1
  name: currencyconfigserver
spec: 
  strategy: # Default, so usually not specified
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1  # specifies the maximum number of Pods that can be created over the desired number of Pods
      maxUnavailable: 25% #specifies the maximum number of Pods that can be unavailable during the update process
  replicas: 1
  selector: 
    matchLabels: 
      app: currencyconfigserver
      version: v1
  template: 
    metadata: 
      labels: 
        app: currencyconfigserver
        version: v1

    spec: 

      containers: 
        - 
          image: "munawarhassan/currencyconfigserver:latest"
          imagePullPolicy: Always
          name: currencyconfigserver
          ports:  
          - name: httpport
            containerPort: 8888
            hostPort: 8888      
  

              
                    